services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-nlw-connect
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3336:3306'
    networks:
      - nlw-connect-network
networks:
  nlw-connect-network:
    driver: bridge